"""create cosmogram table

Revision ID: c142659a903c
Revises: 85cc1b11fedc
Create Date: 2024-11-14 23:26:08.611372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c142659a903c'
down_revision: Union[str, None] = '85cc1b11fedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cosmogram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('planets', sa.JSON(), nullable=True),
    sa.Column('ascendant', sa.Float(), nullable=True),
    sa.Column('cusps', sa.JSON(), nullable=True),
    sa.Column('aspects', sa.JSON(), nullable=True),
    sa.Column('ic', sa.Float(), nullable=True),
    sa.Column('ds', sa.Float(), nullable=True),
    sa.Column('mc', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cosmogram')
    # ### end Alembic commands ###
